{exec} = require 'child_process'
Rehab = require '../../lib/rehab'

task 'build', 'Build coffee2js using Rehab', sbuild = ->
  console.log "Building project from src/*.coffee to lib/app.js"

  files = new Rehab().process './src'
  
  to_single_file = "--join lib/app.js"
  from_files = "--compile #{files.join ' '}"

  exec "coffee #{to_single_file} #{from_files}", (err, stdout, stderr) ->
    throw err if err